### ISSUE TITLE
amis-editor升级到6.9版本之后，控制台有个模块会报错

### ISSUE THREAD

**Issue by younglifestyle** [h7ml/amis-vite-react#5]
![image](https://github.com/user-attachments/assets/3d245541-294d-4cad-85c3-21cee14d0022)

**Comment by younglifestyle** [comment]
好像没有升级，当前版本也存在

**Comment by h7ml** [comment]
来个最小可复现案例。我看看怎么个事？

**Comment by younglifestyle** [comment]
直接运行本仓库会出现，我查了应该是使用vite，但是monaco editor引用的问题

**Comment by h7ml** [comment]
> 直接运行本仓库会出现，我查了应该是使用vite，但是monaco editor引用的问题

无法复现该问题。

**Comment by h7ml** [comment]
当前项目仓库 "amis-editor"为一年前的版本 "^5.3.0"  6.9为2024年12月1日的版本。 可以看看      "amis-editor": "^6.5.0"的使用方式
https://github.com/zwbuber/react-amis-editor/blob/master/src/editor/editor.tsx

**Comment by h7ml** [comment]
> 当前项目仓库 "amis-editor"为一年前的版本 "^5.3.0" 6.9为2024年12月1日的版本。 可以看看 "amis-editor": "^6.5.0"的使用方式 https://github.com/zwbuber/react-amis-editor/blob/master/src/editor/editor.tsx

他的这个仓库，我部署后的地址是 https://react-amis-editor.vercel.app/
